name: consumer
description: consumer is like react-consumer state manage, use Stream at dart, consumer have memo and shoudWidgetUpdate function to intercept update.
version: 1.0.4
author: pillar<pillar@gmail.com>
homepage: https://github.com/ymzuiku/flutter_consumer

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  #  entangle:
  #    path: /Users/pillar/work/darts/dart_entangle
  flutter:
    sdk: flutter
